#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * One-shot importer for disc flight data.
 *
 * Source: https://db.theaceholes.no/ — the entire dataset is inlined in the
 * page HTML as a JS array literal, so no DOM rendering is required.
 *
 * Outputs:
 *   - src/data/discs.json                   (committed snapshot for fast first-paint)
 *   - supabase/migrations/002_seed_discs.sql (table + RLS + bulk INSERT)
 *
 * Run with:  node scripts/import-discs.mjs
 * Optional:  node scripts/import-discs.mjs --html /tmp/aceholes_index.html
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const SOURCE_URL = 'https://db.theaceholes.no/'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

const args = Object.fromEntries(
  process.argv
    .slice(2)
    .map((a, i, arr) => (a.startsWith('--') ? [a.slice(2), arr[i + 1]] : null))
    .filter(Boolean),
)

async function getHtml() {
  if (args.html) {
    console.log(`[import] reading local HTML: ${args.html}`)
    return await readFile(args.html, 'utf8')
  }
  console.log(`[import] fetching ${SOURCE_URL}`)
  const res = await fetch(SOURCE_URL)
  if (!res.ok) throw new Error(`Fetch failed: ${res.status} ${res.statusText}`)
  return await res.text()
}

const ROW_RE =
  /\{manufacturer:"([^"]+)",model:"([^"]+)",plastic:"([^"]*)",type:"([^"]+)",speed:(-?[\d.]+),glide:(-?[\d.]+),turn:(-?[\d.]+),fade:(-?[\d.]+),weight:"([^"]*)"\}/g

function parse(html) {
  const rows = []
  let m
  while ((m = ROW_RE.exec(html))) {
    rows.push({
      manufacturer: m[1],
      model: m[2],
      plastic: m[3],
      type: m[4],
      speed: Number(m[5]),
      glide: Number(m[6]),
      turn: Number(m[7]),
      fade: Number(m[8]),
      weight: m[9],
    })
  }
  return rows
}

function dedupeMolds(rows) {
  // Plastic variants in the source share flight numbers for the same mold —
  // collapse to one row per (manufacturer, model). Keep the first occurrence.
  const seen = new Map()
  for (const r of rows) {
    const k = `${r.manufacturer}|${r.model}`
    if (!seen.has(k)) seen.set(k, r)
  }
  return [...seen.values()]
}

function dropPlaceholders(rows) {
  // Source publishes 0/0/0/0 for discs whose flight numbers haven't been
  // verified yet. Feeding zeros into the recommender produces nonsense, so
  // skip them entirely until they get real values upstream.
  return rows.filter(r => !(r.speed === 0 && r.glide === 0 && r.turn === 0 && r.fade === 0))
}

function brandQualifyNames(rows) {
  // When the same model name appears under multiple manufacturers, the brand
  // that sorts first alphabetically keeps the bare name; the rest get a
  // "Model (Brand)" suffix. Deterministic and stable across imports.
  const brandsByModel = new Map()
  for (const r of rows) {
    if (!brandsByModel.has(r.model)) brandsByModel.set(r.model, new Set())
    brandsByModel.get(r.model).add(r.manufacturer)
  }

  return rows.map(r => {
    const brands = brandsByModel.get(r.model)
    if (brands.size === 1) return { ...r, displayName: r.model }
    const sorted = [...brands].sort()
    return {
      ...r,
      displayName:
        r.manufacturer === sorted[0] ? r.model : `${r.model} (${r.manufacturer})`,
    }
  })
}

function toAppDiscs(rows) {
  // Shape that matches src/types.ts -> Disc, plus optional `type` and `weight`.
  return rows
    .map(r => ({
      name: r.displayName,
      brand: r.manufacturer,
      type: r.type,
      speed: r.speed,
      glide: r.glide,
      turn: r.turn,
      fade: r.fade,
      ...(r.weight ? { weight: r.weight } : {}),
    }))
    .sort((a, b) => {
      if (a.brand !== b.brand) return a.brand.localeCompare(b.brand)
      return a.name.localeCompare(b.name)
    })
}

function sqlEscape(s) {
  return s.replace(/'/g, "''")
}

function buildSeedSql(discs) {
  const header = `-- Disc catalog
-- Generated by scripts/import-discs.mjs from ${SOURCE_URL}
-- Re-run the script and re-apply this migration to refresh the catalog.

create table if not exists public.discs (
  id uuid primary key default gen_random_uuid(),
  name text not null,                            -- brand-qualified display name (storage key for bag_discs.disc_name)
  brand text not null,
  type text not null check (type in ('Putter','Midrange','Fairway','Distance')),
  speed numeric not null,
  glide numeric not null,
  turn numeric not null,
  fade numeric not null,
  weight text,                                   -- manufacturer-published gram range, e.g. "150-176"
  created_by uuid references auth.users(id),     -- null for seeded rows, set for user-added discs
  created_at timestamptz not null default now(),
  unique (name)
);

-- Tolerant of re-runs against pre-existing schemas (e.g. a previous 002 without these columns).
alter table public.discs add column if not exists weight text;
alter table public.discs add column if not exists created_by uuid references auth.users(id);

create index if not exists discs_brand_idx on public.discs (brand);
create index if not exists discs_type_idx on public.discs (type);

alter table public.discs enable row level security;

-- Reference data: world-readable.
drop policy if exists "discs_select_all" on public.discs;
create policy "discs_select_all" on public.discs for select using (true);

-- Any authenticated user can add a new disc; they must own the row (created_by = self).
drop policy if exists "discs_insert_authenticated" on public.discs;
create policy "discs_insert_authenticated" on public.discs
  for insert to authenticated
  with check (auth.uid() = created_by);

-- Idempotent refresh: clear and re-seed.
truncate table public.discs;

insert into public.discs (name, brand, type, speed, glide, turn, fade, weight) values
`

  const rows = discs
    .map(d => {
      const weight = d.weight ? `'${sqlEscape(d.weight)}'` : 'null'
      return `  ('${sqlEscape(d.name)}', '${sqlEscape(d.brand)}', '${sqlEscape(d.type)}', ${d.speed}, ${d.glide}, ${d.turn}, ${d.fade}, ${weight})`
    })
    .join(',\n')

  return header + rows + ';\n'
}

async function main() {
  const html = await getHtml()

  const raw = parse(html)
  console.log(`[import] parsed ${raw.length} rows from source`)

  const molds = dedupeMolds(raw)
  console.log(`[import] ${molds.length} unique molds after plastic-variant dedupe`)

  const real = dropPlaceholders(molds)
  console.log(`[import] ${real.length} molds with real flight numbers`)

  const named = brandQualifyNames(real)
  const collisions = named.filter(r => r.displayName !== r.model).length
  console.log(`[import] ${collisions} names brand-qualified for cross-brand collisions`)

  const discs = toAppDiscs(named)

  const jsonPath = join(ROOT, 'src/data/discs.json')
  await mkdir(dirname(jsonPath), { recursive: true })
  await writeFile(jsonPath, JSON.stringify(discs, null, 2) + '\n', 'utf8')
  console.log(`[import] wrote ${jsonPath}`)

  const sqlPath = join(ROOT, 'supabase/migrations/002_seed_discs.sql')
  await mkdir(dirname(sqlPath), { recursive: true })
  await writeFile(sqlPath, buildSeedSql(discs), 'utf8')
  console.log(`[import] wrote ${sqlPath}`)

  console.log(`[import] done. ${discs.length} discs ready.`)
}

main().catch(err => {
  console.error('[import] FAILED:', err)
  process.exit(1)
})
